packages:
  - name: personas
    functions:
      - name: generate
        runtime: nodejs:18
        web: raw
        environment:
          OPENAI_API_KEY: ${OPENAI_API_KEY}
        limits:
          timeout: 30000
          memory: 512
        parameters:
          cors:
            enabled: true
            allowOrigin: "*"
            allowMethods: "POST, OPTIONS"
            allowHeaders: "Content-Type"
        annotations:
          final: true